// GENERATED by scripts/gen-authz.mjs from the project's OpenAPI contracts
// (specs/design/components/*/openapi.yaml and
// specs/design/components/*/dependencies/*.openapi.yaml).
// Do not edit by hand, and do not retype any of these values anywhere else.
// Re-run `npm run gen` after a contract changes. COMMIT this file: the
// per-component image build cannot see the specs tree.
//
// This table is what a screen is gated on. src/authz/screens.ts names the
// operation each screen LOADS; holding that operation's scope is what makes the
// screen reachable. Nothing else in the app decides that.

import type { Scope } from "./roles.gen";

/** What the gateway demands of a caller before it will pass an operation on. */
export type OperationRequirement =
  | { readonly kind: "public" }
  | { readonly kind: "signedIn" }
  | { readonly kind: "scope"; readonly scope: Scope };

/** "<METHOD> <path template>" as the contract spells it, e.g. "GET /me/claims". Sorted. */
export type OperationKey =
  | "GET /correspondence"
  | "GET /correspondence/{correspondenceId}"
  | "GET /correspondence/{correspondenceId}/movements"
  | "GET /departments"
  | "GET /me/department/correspondence"
  | "GET /me/department/correspondence/{correspondenceId}"
  | "GET /me/department/correspondence/{correspondenceId}/movements"
  | "GET /public/departments/sla-performance"
  | "GET /users"
  | "PATCH /departments/{departmentId}"
  | "PATCH /me/department/correspondence/{correspondenceId}/status"
  | "POST /correspondence"
  | "POST /correspondence/attachment-upload-url"
  | "POST /correspondence/{correspondenceId}/reassign"
  | "POST /correspondence/{correspondenceId}/route"
  | "POST /departments"
  | "POST /departments/{departmentId}/deactivate"
  | "POST /me/department/correspondence/{correspondenceId}/close"
  | "POST /me/department/correspondence/{correspondenceId}/response"
  | "POST /users/onboard";

export const OPERATIONS: Record<OperationKey, OperationRequirement> = {
  "GET /correspondence": { kind: "scope", scope: "correspondence:read-all" },
  "GET /correspondence/{correspondenceId}": { kind: "scope", scope: "correspondence:read-all" },
  "GET /correspondence/{correspondenceId}/movements": { kind: "scope", scope: "correspondence:read-all" },
  "GET /departments": { kind: "scope", scope: "departments:read" },
  "GET /me/department/correspondence": { kind: "scope", scope: "correspondence:read" },
  "GET /me/department/correspondence/{correspondenceId}": { kind: "scope", scope: "correspondence:read" },
  "GET /me/department/correspondence/{correspondenceId}/movements": { kind: "scope", scope: "correspondence:read" },
  "GET /public/departments/sla-performance": { kind: "public" },
  "GET /users": { kind: "scope", scope: "users:read" },
  "PATCH /departments/{departmentId}": { kind: "scope", scope: "departments:manage" },
  "PATCH /me/department/correspondence/{correspondenceId}/status": { kind: "scope", scope: "correspondence:update-status" },
  "POST /correspondence": { kind: "scope", scope: "correspondence:log" },
  "POST /correspondence/attachment-upload-url": { kind: "signedIn" },
  "POST /correspondence/{correspondenceId}/reassign": { kind: "scope", scope: "correspondence:reassign" },
  "POST /correspondence/{correspondenceId}/route": { kind: "scope", scope: "correspondence:route" },
  "POST /departments": { kind: "scope", scope: "departments:manage" },
  "POST /departments/{departmentId}/deactivate": { kind: "scope", scope: "departments:manage" },
  "POST /me/department/correspondence/{correspondenceId}/close": { kind: "scope", scope: "correspondence:close" },
  "POST /me/department/correspondence/{correspondenceId}/response": { kind: "scope", scope: "correspondence:respond" },
  "POST /users/onboard": { kind: "scope", scope: "users:onboard" },
};

export function isOperationKey(value: string): value is OperationKey {
  return Object.prototype.hasOwnProperty.call(OPERATIONS, value);
}
