// GENERATED by scripts/gen-authz.mjs from specs/design/security.json.
// Do not edit by hand, and do not retype any of these values anywhere else.
// Re-run `npm run gen` after the design changes. COMMIT this file: the
// per-component image build cannot see the specs tree.

export type Scope =
  | "correspondence:close"
  | "correspondence:log"
  | "correspondence:read"
  | "correspondence:read-all"
  | "correspondence:reassign"
  | "correspondence:respond"
  | "correspondence:route"
  | "correspondence:update-status"
  | "departments:manage"
  | "departments:read"
  | "users:onboard"
  | "users:read";

export type Role =
  | "Admin"
  | "DepartmentOfficer"
  | "RegistryOfficer"
  | "Supervisor";

/** Every handle the catalog declares, sorted. */
export const SCOPES: readonly Scope[] = ["correspondence:close", "correspondence:log", "correspondence:read", "correspondence:read-all", "correspondence:reassign", "correspondence:respond", "correspondence:route", "correspondence:update-status", "departments:manage", "departments:read", "users:onboard", "users:read"];

/** Every role a person can hold, sorted. Service-kind roles are not here. */
export const ROLES: readonly Role[] = ["Admin", "DepartmentOfficer", "RegistryOfficer", "Supervisor"];

/** What each role grants. heldRoles() projects the caller's scopes through this. */
export const ROLE_GRANTS: Record<Role, readonly Scope[]> = {
  "Admin": ["departments:manage", "departments:read", "users:onboard", "users:read"],
  "DepartmentOfficer": ["correspondence:close", "correspondence:read", "correspondence:respond", "correspondence:update-status", "departments:read"],
  "RegistryOfficer": ["correspondence:log", "correspondence:read-all", "correspondence:reassign", "correspondence:route", "departments:read"],
  "Supervisor": ["correspondence:read-all", "correspondence:reassign", "departments:read"],
};

/** The directory groups a role is assigned to — what NoAccess tells a user to ask for. */
export const ROLE_ASSIGN_TO: Record<Role, readonly string[]> = {
  "Admin": ["CorrespondenceAdmins"],
  "DepartmentOfficer": ["DepartmentOfficers"],
  "RegistryOfficer": ["RegistryOfficers"],
  "Supervisor": ["Supervisors"],
};

/** The roles that can hand this one out — who NoAccess tells a user to ask. */
export const ROLE_ASSIGNABLE_BY: Record<Role, readonly string[]> = {
  "Admin": [],
  "DepartmentOfficer": [],
  "RegistryOfficer": [],
  "Supervisor": [],
};

export function isScope(value: string): value is Scope {
  return (SCOPES as readonly string[]).includes(value);
}
